databases:
  - name: ObjectDetectiondb
    plan: free
    databaseName: ides_productdetails
    user: suvarna

services:
  - type: web
    plan: free
    name: ObjectDetection
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ObjectDetection.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgres://suvarna:WtP73JWm7n1DOlCcVAsdngc7xL9DNf5C@dpg-cplbrp0cmk4c739lfam0-a/ides_productdetails
        fromDatabase:
          name: ObjectDetectiondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4